import Head from 'next/head'
import Clients from '../components/Clients'
import Collaboration from '../components/Collaboration'
import Footer from '../components/Footer'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Remote from '../components/Remote'
import Talents from '../components/Talents'
import Talk from '../components/Talk'
import Work from '../components/Work'

export default function Home () {
  return (
    <div className=''>
      <Head>
        <title> Agency</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full overflow-hidden'>
        <Navbar />
        <Main />
        <Remote />
        <Collaboration />
        <Talents />
        <Work />
        <Clients />
        <Talk />
        <Footer />
      </main>
    </div>
  )
}
